variable "db_name" {
  type        = string
  description = "The name of the database to be created."
}

variable "location" {
  type        = string
  description = "The location/region where the database and server are created. Changing this forces a new resource to be created."
}

variable "sql_admin_username" {
  type        = string
  description = "The administrator username of the SQL Server."
}

variable "sql_password" {
  type        = string
  description = "The administrator password of the SQL Server."
  sensitive   = true
}

variable "collation" {
  type        = string
  default     = "SQL_Latin1_General_CP1_CI_AS"
  description = "The collation for the database. Default is SQL_Latin1_General_CP1_CI_AS"
}

variable "create_resource_group" {
  type        = bool
  default     = true
  description = "Create a new resource group with name `var.resource_group_name`, or just use it as resource group's name. Default to `true`. Changing this forces a new resource to be created."
}

variable "db_sku_name" {
  type        = string
  default     = "Basic"
  description = "Specifies the name of the SKU used by the database. Changing this from the HyperScale service tier to another service tier will create a new resource."
}

variable "end_ip_address" {
  type        = string
  default     = "0.0.0.0"
  description = "Defines the end IP address used in your database firewall rule."
}

variable "resource_group_name" {
  type        = string
  default     = "myapp-rg"
  description = "Default resource group name that the database will be created in."
}

variable "server_version" {
  type        = string
  default     = "12.0"
  description = "The version for the database server. Valid values are: 2.0 (for v11 server) and 12.0 (for v12 server)."
}

variable "sql_aad_administrator" {
  type = object({
    login_username              = string
    object_id                   = string
    tenant_id                   = optional(string)
    azuread_authentication_only = optional(bool)
  })
  default     = null
  description = <<-EOF
  object({
    login_username = (Required) The login name of the principal to set as the server administrator
    object_id = (Required) The ID of the principal to set as the server administrator
    tenant_id = (Optional) The Azure Tenant ID
    azuread_authentication_only = (Optional) Specifies whether only AD Users and administrators can be used to login (`true`) or also local database users (`false`).
  })
EOF
}

variable "start_ip_address" {
  type        = string
  default     = "0.0.0.0"
  description = "Defines the start IP address used in your database firewall rule."
}

variable "tags" {
  type = map(string)
  default = {
    tag1 = ""
    tag2 = ""
  }
  description = "The tags to associate with your network and subnets."
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}
